/**
 * Maps to the live `ai_analysis` Supabase table.
 * Columns: id, application_id, readiness_score, missing_documents,
 * recommendations, created_at, strengths, weaknesses
 */
export interface Analysis {
  id: string;
  application_id: string;
  readiness_score: number | null;
  missing_documents: MissingDocumentEntry[] | null;
  recommendations: StoredRecommendations | string[] | null;
  strengths: string[] | null;
  weaknesses: string[] | null;
  created_at: string;
}

export type ProfileStrength = 'Strong' | 'Moderate' | 'Needs Improvement';

export type ReadinessStatus = 'Ready' | 'Moderate Readiness' | 'Needs Improvement' | 'Not Ready';

/** Applicant profile extracted during analysis. */
export interface ApplicantInfo {
  name: string;
  email: string;
  phone: string;
  target_program: string;
  target_university: string;
}

/** Document entry within an analysis snapshot. */
export interface AnalysisDocumentEntry {
  name: string;
  status: 'complete' | 'incomplete' | 'pending';
  date?: string;
}

/** Missing document with priority for recommendations. */
export interface MissingDocumentEntry {
  name: string;
  priority: 'high' | 'medium' | 'low';
}

/** Missing requirement identified during analysis. */
export interface MissingRequirementEntry {
  name: string;
  category: string;
  priority: 'high' | 'medium' | 'low';
}

/** Canonical three-level document completeness classification. */
export type DocumentCompletenessLevel = 'COMPLETE' | 'PARTIAL' | 'MISSING';

/** Professional per-document evaluation schema (canonical). */
export interface DocumentEvaluationSchema {
  document_name: string;
  document_type: string;
  uploaded: boolean;
  quality_score: number;
  completeness: DocumentCompletenessLevel;
  strengths: string[];
  weaknesses: string[];
  missing_information: string[];
  suggestions: string[];
  extracted_information: Record<string, unknown>;
  confidence: number;
}

/** Per-document evaluation from the AI analysis pipeline. */
export interface DocumentEvaluation {
  name: string;
  status: 'present' | 'missing';
  notes: string;
  completeness?: string;
  quality?: string;
  missing_information?: string[];
  suggestions?: string[];
  /** Extended professional evaluation fields. */
  document_name?: string;
  document_type?: string | null;
  uploaded?: boolean;
  quality_score?: number;
  completeness_level?: DocumentCompletenessLevel;
  strengths?: string[];
  weaknesses?: string[];
  extracted_information?: Record<string, unknown>;
  confidence?: number;
}

/** Checklist item generated by the AI pipeline. */
export interface ChecklistEntry {
  item: string;
  completed: boolean;
}

/** Eligibility comparison row for the readiness report table. */
export interface EligibilityComparisonRow {
  requirement_name: string;
  required_value: string | null;
  applicant_value: string | null;
  status: string;
  confidence: number;
  explanation: string;
  suggested_action: string | null;
  // Legacy aliases for backward compatibility
  requirement?: string;
  requirement_value?: string | null;
  reason?: string;
}

/** Full document assessment entry in the readiness report. */
export interface DocumentAssessmentEntry {
  name: string;
  document_type: string | null;
  uploaded: boolean;
  completeness: string;
  quality: string;
  missing_information: string[];
  suggestions: string[];
  /** Extended professional evaluation fields. */
  document_name?: string | null;
  quality_score?: number | null;
  completeness_level?: string | null;
  strengths: string[];
  weaknesses: string[];
  extracted_information: Record<string, unknown>;
  confidence?: number | null;
}

/** Timeline entry in the readiness report. */
export interface ReportTimelineEntry {
  date: string;
  event: string;
  priority: string;
}

/** Final verdict section of the readiness report. */
export interface FinalVerdict {
  summary: string;
  recommendation: string;
  confidence: string;
}

/** Overall readiness score and status. */
export interface OverallReadiness {
  readiness_score: number;
  status: string;
}

/** Personal information extracted from documents. */
export interface PersonalInformation {
  full_name: string | null;
  nationality: string | null;
  passport_number: string | null;
  passport_expiry: string | null;
}

/** Academic information extracted from documents. */
export interface AcademicInformation {
  university: string | null;
  degree: string | null;
  major: string | null;
  gpa: string | null;
  graduation_year: string | null;
}

/** Language test scores extracted from documents. */
export interface LanguageScores {
  test_type: string | null;
  overall_score: string | null;
  reading: string | null;
  listening: string | null;
  writing: string | null;
  speaking: string | null;
}

/** Applicant profile summary sections. */
export interface ApplicantProfileSummary {
  personal_information: PersonalInformation;
  academic_information: AcademicInformation;
  language_scores: LanguageScores;
  skills: string[];
  experience: string[];
  leadership: string[];
}

/** Full professional AI Readiness Report. */
export interface ReadinessReport {
  overall_readiness: OverallReadiness;
  executive_summary: string;
  applicant_profile_summary: ApplicantProfileSummary;
  eligibility_comparison: EligibilityComparisonRow[];
  missing_requirements: MissingRequirementEntry[];
  document_assessment: DocumentAssessmentEntry[];
  missing_documents: MissingDocumentEntry[];
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
  timeline: ReportTimelineEntry[];
  final_verdict: FinalVerdict;
}

/** Extended analysis fields stored inside `recommendations` JSONB. */
export interface StoredRecommendations {
  summary: string[];
  improvement_suggestions: string[];
  recommended_next_steps: string[];
  missing_requirements: MissingRequirementEntry[];
  document_evaluations: DocumentEvaluation[];
  uploaded_documents: AnalysisDocumentEntry[];
  checklist: ChecklistEntry[];
  timeline: import('@/types/timeline').TimelineEventSummary[];
  applicant_info: ApplicantInfo;
  profile_strength: ProfileStrength;
  scholarship_name: string | null;
  eligibility_score: number;
  /** @deprecated Use readiness_report.overall_readiness.status */
  readiness_status?: ReadinessStatus;
  applicant_profile?: Record<string, unknown> | null;
  requirement_comparisons?: Array<{
    field: string;
    requirement: string | null;
    applicant: string | null;
    status: string;
    reason: string;
  }>;
  readiness_report?: ReadinessReport;
  final_verdict?: FinalVerdict;
}

/** Payload for inserting an analysis record. */
export interface AnalysisInsert {
  application_id: string;
  readiness_score: number;
  missing_documents: MissingDocumentEntry[];
  recommendations: StoredRecommendations;
  strengths: string[];
  weaknesses: string[];
}

/** Full analysis result shape returned to the UI. */
export interface AnalysisResult {
  applicant_info: ApplicantInfo;
  uploaded_documents: AnalysisDocumentEntry[];
  missing_documents: MissingDocumentEntry[];
  missing_requirements: MissingRequirementEntry[];
  checklist: ChecklistEntry[];
  timeline: import('@/types/timeline').TimelineEventSummary[];
  eligibility_score: number;
  profile_strength: ProfileStrength;
  readiness_status: ReadinessStatus;
  strengths: string[];
  weaknesses: string[];
  improvement_suggestions: string[];
  recommended_next_steps: string[];
  scholarship_name: string | null;
  document_evaluations: DocumentEvaluation[];
  eligibility_comparison: EligibilityComparisonRow[];
  applicant_profile_summary: ApplicantProfileSummary | null;
  document_assessment: DocumentAssessmentEntry[];
  final_verdict: FinalVerdict | null;
  readiness_report: ReadinessReport | null;
  /** @deprecated Use eligibility_score */
  readiness_score: number;
  recommendations: string[];
}
